# Generated by Django 5.1.7 on 2025-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('ru', 'Russian')], default='en', max_length=2),
        ),
    ]
