# Generated by Django 5.1.7 on 2025-03-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_flower_description_uk_flower_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='language',
        ),
    ]
