# Generated by Django 5.1.7 on 2025-03-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_remove_flower_description_uk_remove_flower_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
